In [1]:
import torch, io
import json

with open(f"model.pt", "rb") as f:
    model = f.read()

torch.jit.load(io.BytesIO(eval(json.loads(json.dumps({"token": 'test', "model": str(model)}))['model'])))

RecursiveScriptModule(
  original_name=SimpleModel
  (fc1): RecursiveScriptModule(original_name=Linear)
  (relu): RecursiveScriptModule(original_name=ReLU)
  (fc2): RecursiveScriptModule(original_name=Linear)
)

In [22]:
from util import *

db = connReq()
collection = db["posts"]
collection.insert_one({"token": 'test', "model": str(model)})

document = collection.find({"token": 'test'})
document[0]

{'_id': ObjectId('651d65eb79191659175c0340'),
 'token': 'test',
 'model': 'b\'PK\\x03\\x04\\x00\\x00\\x08\\x08\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x0c\\x00\\x16\\x00model/data/0FB\\x12\\x00ZZZZZZZZZZZZZZZZZZQ\\x87\\xb2\\xbcp\\xa6p\\xbcd0\\x81<a\\x18W\\xbe\\x8aJ\\xd8\\xbb\\xa3I\\x85\\xba\\xa1\\xca\\xd2<\\xaf_(\\xbe\\x94\\x92\\xb0\\xb9\\xbf\\x91\\xc0\\xbd\\xd4\\x11.\\xbd\\x04\\x99\\xbd<\\x99a\\x19<\\xef\\t3\\xbe\\x9c)\\xb2=\\x9f\\xe48\\xbd\\xb6\\xf3\\xfa\\xbd\\x02\\xd9\\x98\\xbd\\x94`Y>\\xc2/F\\xbe-\\rs\\xbc\\xfb\\xae\\xa6;R\\x15\\xfd\\xbdVL\\x8a\\xbd\\xcb\\xc9\\xde\\xbc\\x97\\xc4\\xe0<~)\\n>1\\xcb\\x1e\\xbeo\\x1f.>\\x0b]\\xf9\\xbc\\xc7+;>\\xd2\\x8a\\xe0\\xbb\\xa2c\\xf9<\\x87QB\\xbe\\x1e\\x9d\\x16=\\xf3\\xb2K\\xbe\\x8d\\xbdE=\\xeb2\\x16>\\xc7!O>c\\xb0\\x1b\\xbe\\xc9W\\xe5\\xbd\\x91*B>\\xd4\\xba\\xce\\xbc\\xd1/\\n>\\xd5\\xea\\x1a=\\xc8}^\\xbe\\x80\\x92T=\\xa1!e>\\xfb\\xaf\\x84=\\x07\\xe4->\\x91\\xec\\x80=\\xdb[\\xa9\\xbd4\\xd8\\x19\\x

In [18]:
''.join(random.choices(string.ascii_letters + string.digits, k=16))

'CnIwJYCjrwObS7Re'

In [1]:
from fedClient import *

with open(f"best_49.pt", "rb") as f:
    model_bytes = f.read()

flAggregation('http://fl-aggregator.kro.kr', capacity = 1, model_bytes = model_bytes)

c:\Users\uoon9\.conda\envs\gpu_env\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


L8T7j4vsveAni3HT
Connected to Flask-SocketIO server


packet queue is empty, aborting


In [3]:
flAggregation('http://fl-aggregator.kro.kr', token = 'v2aK1YsrMNdzs0nI', capacity = 2, model_bytes = 50)

v2aK1YsrMNdzs0nI
Connected to Flask-SocketIO server
50.0


In [1]:
import torch, io

with open(f"best_49.pt", "rb") as f:
    model_bytes = f.read()


model = torch.load(io.BytesIO(model_bytes))
model

c:\Users\uoon9\.conda\envs\gpu_env\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


ModuleNotFoundError: No module named 'models'

In [2]:
import torch
torch.hub.load('ultralytics/yolov5', 'yolov5m', )
model = torch.load('yolov5m.pt')
model

Using cache found in C:\Users\uoon9/.cache\torch\hub\ultralytics_yolov5_master
YOLOv5  2023-10-12 Python-3.10.10 torch-1.11.0+cpu CPU

Fusing layers... 
YOLOv5m summary: 290 layers, 21172173 parameters, 0 gradients
Adding AutoShape... 


{'epoch': -1,
 'best_fitness': None,
 'model': DetectionModel(
   (model): Sequential(
     (0): Conv(
       (conv): Conv2d(3, 48, kernel_size=(6, 6), stride=(2, 2), padding=(2, 2), bias=False)
       (bn): BatchNorm2d(48, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
       (act): SiLU(inplace=True)
     )
     (1): Conv(
       (conv): Conv2d(48, 96, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
       (bn): BatchNorm2d(96, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
       (act): SiLU(inplace=True)
     )
     (2): C3(
       (cv1): Conv(
         (conv): Conv2d(96, 48, kernel_size=(1, 1), stride=(1, 1), bias=False)
         (bn): BatchNorm2d(48, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
         (act): SiLU(inplace=True)
       )
       (cv2): Conv(
         (conv): Conv2d(96, 48, kernel_size=(1, 1), stride=(1, 1), bias=False)
         (bn): BatchNorm2d(48, eps=0.001, momentum=0.03, affine=True, track_

In [3]:
model1 = torch.load('best_49.pt')
model2 = torch.load('best_50.pt')
model3 = torch.load('best_51.pt')

In [4]:
import copy
model = copy.deepcopy(model1)

model['model'].state_dict()

OrderedDict([('model.0.conv.weight',
              tensor([[[[-3.93677e-02, -1.39893e-01, -7.67822e-02, -4.53491e-02,  7.50732e-03,  3.93677e-02],
                        [-1.77124e-01, -1.62964e-01,  7.64771e-02, -6.05774e-02, -8.02517e-04,  1.25610e-01],
                        [-2.22778e-01, -2.33765e-02,  2.36572e-01, -1.08948e-02,  1.92566e-02,  1.74683e-01],
                        [-1.82007e-01, -2.13501e-01, -2.63184e-01, -1.23596e-01,  1.89087e-01,  1.52466e-01],
                        [-8.88062e-02, -1.27930e-01, -1.71143e-01,  1.93726e-01,  3.95508e-01,  1.32935e-01],
                        [-7.65381e-02, -3.07922e-02,  1.78223e-02,  1.24573e-01,  7.08618e-02,  8.80737e-02]],
              
                       [[-2.57263e-02, -7.71484e-02, -1.75476e-02, -1.21918e-02,  2.81067e-02,  2.82440e-02],
                        [-1.06384e-01, -2.16827e-02,  2.25342e-01, -1.76849e-02, -3.98254e-02,  4.58679e-02],
                        [-6.43311e-02,  1.78589e-01,  4.08691e-01, 

In [5]:
models = [model1['model'], model2['model'], model3['model']]

In [6]:
fed_dict = {}
for key in model['model'].state_dict().keys():
    fed_dict[key] = sum([model1['model'].state_dict()[key], model2['model'].state_dict()[key], model3['model'].state_dict()[key]])/3

model['model'].load_state_dict(fed_dict)
model['model'].state_dict()

OrderedDict([('model.0.conv.weight',
              tensor([[[[-2.91290e-02, -1.33911e-01, -7.14722e-02, -3.78113e-02,  1.50757e-02,  4.62952e-02],
                        [-1.68335e-01, -1.56738e-01,  8.11157e-02, -5.59082e-02,  5.87463e-03,  1.29883e-01],
                        [-2.22534e-01, -2.22168e-02,  2.39258e-01, -1.06201e-02,  1.86157e-02,  1.70898e-01],
                        [-1.81274e-01, -2.09595e-01, -2.58057e-01, -1.21765e-01,  1.88599e-01,  1.49048e-01],
                        [-8.61206e-02, -1.23352e-01, -1.69312e-01,  1.93481e-01,  3.93311e-01,  1.29517e-01],
                        [-7.39746e-02, -2.62909e-02,  1.84784e-02,  1.21765e-01,  6.53687e-02,  8.22144e-02]],
              
                       [[-1.90277e-02, -7.49512e-02, -1.75171e-02, -1.09558e-02,  3.00903e-02,  2.92969e-02],
                        [-1.00891e-01, -1.99127e-02,  2.23999e-01, -1.93329e-02, -3.96729e-02,  4.52881e-02],
                        [-6.54297e-02,  1.76147e-01,  4.06006e-01, 

In [7]:
torch.save(model, 'fed.pt')

In [10]:
torch.load('fed.pt')['model'].state_dict()

OrderedDict([('model.0.conv.weight',
              tensor([[[[-2.91290e-02, -1.33911e-01, -7.14722e-02, -3.78113e-02,  1.50757e-02,  4.62952e-02],
                        [-1.68335e-01, -1.56738e-01,  8.11157e-02, -5.59082e-02,  5.87463e-03,  1.29883e-01],
                        [-2.22534e-01, -2.22168e-02,  2.39258e-01, -1.06201e-02,  1.86157e-02,  1.70898e-01],
                        [-1.81274e-01, -2.09595e-01, -2.58057e-01, -1.21765e-01,  1.88599e-01,  1.49048e-01],
                        [-8.61206e-02, -1.23352e-01, -1.69312e-01,  1.93481e-01,  3.93311e-01,  1.29517e-01],
                        [-7.39746e-02, -2.62909e-02,  1.84784e-02,  1.21765e-01,  6.53687e-02,  8.22144e-02]],
              
                       [[-1.90277e-02, -7.49512e-02, -1.75171e-02, -1.09558e-02,  3.00903e-02,  2.92969e-02],
                        [-1.00891e-01, -1.99127e-02,  2.23999e-01, -1.93329e-02, -3.96729e-02,  4.52881e-02],
                        [-6.54297e-02,  1.76147e-01,  4.06006e-01, 